### PR TITLE
integrated WebMemex icon and minor design tweak to popup #130

### PR DESCRIPTION
**Pull request by bnvk**
**Current State**

2018-02-04-212954_1366x768_scrot

**Proposed Changes**

2018-02-04-212842_1366x768_scrot

Changes include:

* Added official logo to repository in multiple sizes
* Made logo display as favicon, search heading, browser action button, and popup
* Improved styles of popup window
* Better harmonized use of word "memory"

### CODE REVIEW

**Comment by Treora** [comment]
Hey, thanks for working on the ever-lacking design! Reminds me how this project should really get an actual logo, this old sketch of mine embarrasses me every time I see it. But then, maybe seeing it more often will expediate its replacement. ;)

I am not sure yet if I like the term "Web Memories"; at least for me personally, 'memories' has quite a different (more nostalgic/emotional) connotation than 'memory'. Either way, the whole design, functionality and concept of the extension should get upgraded, so whatever we do now is, as you already indicated, best regarded as a stop-gap.

**Comment by bnvk** [comment]
Yes, I would suggest getting proper logo and design work at some stage (in not too far off future) and I'd be happy to help facilitate getting that done as I know FOSS designers :smile: I don't think the one you did is *bad* per se, and is vastly better than the default "plugin" icon, IMHO. 

I agree on "memory" being less than ideal. I went with it as you were already using it and also is closer to "memex" but more friendly. However, I do think "snapshot" is better. Happy to swap this out and re-push.

**Comment by Treora** [comment]
I would like us to create and collect more than just snapshots; if you can create pages, notes, connections between them, I hope it can get closer to a digital memory, worthy of the name memex. But yes, since currently it just makes snapshots, that may be a fine term to use.

**Comment by bnvk** [comment]
@Treora replaced all instances with snapshot if ya wanna merge :)

**Pull request merged**
